# Generated by Django 4.0.10 on 2023-04-09 23:04

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpageimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_page_images', to='blog.blogpage'),
        ),
    ]
